config/routes.rb
Rails.application.routes.draw do
  resources :friends
  get 'friends_serch', to: 'friends#serch'
  devise_for :users
  root 'pages#home'
  get 'page/home'

  resources :users
  get 'profile', to: 'users#profile'
  resources :rooms
  resources :channels
  resources :channels do
    member do
      get 'invite_user_index'
      post 'invite_user'
    end
  end

  resources :messages, only: %i(create edit update destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/channel_user.rb
class ChannelUser < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user

  validates :user_id, uniqueness: { scope: :to_id }, if: :invite_doub?

  scope :established, -> { where(establish: true) }

  private

    def invite_doub?
      establish == false
      apply == true
    end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :channel

  mount_uploader :image, ImageUploader

  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :channel_users
  has_many :channels, through: :channel_users
  accepts_nested_attributes_for :channel_users
  has_many :friends

  mount_uploader :icon_img, ImageUploader

  validates :user_original, uniqueness: true, allow_nil: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :create_monologue_channel

  def create_monologue_channel
    channels.create(name: '自分')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = %i[name email password password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/channels_controller.rb
# frozen_string_literal: true

class ChannelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_channel, only: %i(show destroy invite_user_index invite_user)

  def index
    @channels = current_user.channels
  end

  def show
    @messages = @channel.messages
  end

  def new
    @channel = current_user.channels.new
  end

  def create
    @channel = current_user.channels.new(channel_params)
    if current_user.save
      redirect_to channels_path
    else
      render :new
    end
  end

  def destroy
    @channel.destroy
    redirect_to channels_path
  end

  def invite_user_index
    @users = User.all
  end

  def invite_user
    ChannelUser.create(channel_id: @channel.id, user_id: params[:user_id])
    redirect_to @channel
  end

  private

    def channel_params
      params.require(:channel).permit(:name)
    end

    def set_channel
      @channel = Channel.find(params[:id])
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  add_flash_types :error
  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
    your_friend_ids = current_user.friends.established.pluck(:to_id) +  # 自分から申請して友だちになったやつ
      User.joins(:friends)  # 申請を受け入れて友達になったやつ
        .where(friends: { to_id: current_user.id, establish: true })
        .pluck(:user_id)
    @your_friends = User.where(id: your_friend_ids).order(:name)
    @users_wanting_to_become_friend_with_you = User.joins(:friends)
      .where(friends: { to_id: current_user.id, establish: false })
      .order(:name)
  end

  # GET /friends/new
  def new
    @user = User.where(user_original: params[:uniq])
    @friend = Friend.new()
  end
  # GET /friends/1/edit
  def edit
  end

  def serch
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)
    if @friend.save
      redirect_to friends_serch_path
    elsif Friend.find_by(user_id: friend_params[:user_id], to_id: friend_params[:to_id]).establish?
      redirect_to friends_serch_path, error: ['もう友達だよーん']
    else
      redirect_to friends_serch_path, error: @friend.errors.full_messages
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:user_id, :to_id, :establish, :apply)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message = Message.new(message_params)
    @message.save
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :user_id, :channel_id, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.where(channel_id: params[:id])
  end
end

app/controllers/users_controller.rb
require 'mini_magick'

class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    your_friend_ids = current_user.friends.established.pluck(:to_id) +  # 自分から申請して友だちになったやつ
      User.joins(:friends)  # 申請を受け入れて友達になったやつ
        .where(friends: { to_id: current_user.id, establish: true })
        .pluck(:user_id)
    @your_friends = User.where(id: your_friend_ids).order(:name)
  end

  def edit
  end

  def profile
  end

  def update
    if current_user.update(user_params)
      if params[:user][:icon_img] != nil
        img_resize(400, 400)
        thumb_resize("public/uploads/user/#{params[:user][:icon_img].original_filename}", 100, 100)
      end
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :user_original, :icon_img)
    end

    def img_resize(width, height)
      img = MiniMagick::Image.read(params[:user][:icon_img])
      img.gravity(:center)
      img.resize "#{width}x#{height}"
      img.write "public/uploads/user/#{params[:user][:icon_img].original_filename}"
    end

    def thumb_resize(path, width, height)
      img = MiniMagick::Image.open(path)
      img.gravity(:center)
      img.resize "#{width}x#{height}"
      img.write "public/uploads/user/thumb/#{params[:user][:icon_img].original_filename}"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/img_posts_helper.rb
module ImgPostsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/_uploader.html.slim
= form_for resource, html: { id: 'post_form' } do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :channel_id, value: channel.id
  = f.label "画像をアップロード"
  = f.file_field :image
  = f.submit value: '投稿', id: 'post_image'

app/views/channels/index.html.slim
.container.w-50
  h1 チャンネル一覧
  = link_to 'チャンネルを新規作成する', new_channel_path, class: 'btn btn-info mb-4 text-white'
  = button_tag fa_icon(:trash, text: 'チャンネルを削除'), type: 'button', onclick: 'changeMode()', class: 'btn-sm btn-danger delete-mode pull-right'
  table.table
    thead
      tr
        td ルーム名
        td
        tbody
        - @channels.each do |channel|
          tr
            td = link_to channel.name, channel, class: 'btn btn-outline-primary w-100 link'
            td.text-right = link_to fa_icon(:trash), channel, method: :delete, class: 'btn btn-sm btn-outline-danger delete-btn', data: { confirm: '本当に削除しますか' }

javascript:
  $(() => {
    $('.delete-btn').hide();
  });

  let isEditMode = false;
  const changeMode = () => {
    if (isEditMode)
      $('.delete-btn').hide();
    else
      $('.delete-btn').show();

    isEditMode = !isEditMode;
  };

app/views/channels/invite_user_index.html.slim
.container
  table.table
    thead
      tr
        th 招待するユーザー
        th
    tbody
    - @users.each do |user|
      - next if current_user == user || @channel.users.include?(user)
      tr
        th = link_to user do
          = fa_icon 'user-circle', text: user.name
        th = link_to invite_user_channel_path(@channel, user_id: user.id), method: :post do
          = fa_icon 'plus-square', text: '招待'

app/views/channels/new.html.slim
.container
  h2 チャンネル作成
  = render 'layouts/error_message', resouce: @channel
  = form_for @channel do |f|
    = f.text_field :name, placeholder: "新規チャンネル名"
    = f.submit "チャンネルを作る", class: 'square_btn'

app/views/channels/show.html.slim
= stylesheet_link_tag 'channel'
.container.w-100
  span style='font-size: 32px' Chat room
  - if @channel.name != '自分'
    span.dropdown.pull-right
      = button_tag type: 'button', class: 'btn btn-default dropdown-toggle', id: 'dropdownMenu', data: { toggle: 'dropdown' }, aria: { haspopup: true, expanded: true } do
        span.caret = fa_icon 'user-circle', text: '参加ユーザー'
      ul.dropdown-menu aria-labelledby='dropdownMenu' style='overflow: hidden'
        - @channel.users.each do |user|
          li = link_to  user.name.truncate(10), user, class: 'btn btn-default w-100'
        li.divider role='separator'
        li = link_to invite_user_index_channel_path(@channel), class: 'btn btn-default' do
         = fa_icon 'plus-square', text: '友達を呼ぶ'

  #messages.table data-current-user="#{current_user.id}" data-channel-id="#{params[:id]}"
    = render @messages

  .move

  footer.fixed-bottom
    .container
      #form.text-center
        form
          input type='text' id='text' placeholder='メッセージを入力' data-behavior='channel_speaker' class='mb-5'
          input type='button' name='submit' id='submit' value='送信' data-behavior='channel_speaker'
        = render 'uploader', resource: Message.new, channel: @channel

javascript:
  const crnt_user_id = #{current_user.id};
  $(function () {
    $('#messages').children().each(function () {
      const send_user_id = $(this).data('send-user');
      const direction = crnt_user_id == send_user_id ? 'right' : 'left'
      $(this).addClass(`text-${direction}`);
    });
  });
  // メッセージ追加時
  $('#messages').on('DOMSubtreeModified propertychange', function () {
    const send_user_id = $('#messages .message:last-child').data('send-user');
    move = $('.move').offset().top;
    $(window).scrollTop(move);
    const direction = crnt_user_id == send_user_id ? 'right' : 'left';
    $('#messages .message:last-child').addClass(`text-${direction}`);
  });

app/views/friends/index.html.slim
h1 Listing friends

table
  thead
    tr
      th From user
      th To user
      th Establish
      th Apply
      th
      th
      th

  tbody
    - @friends.each do |friend|
      tr
        td = friend.from_user
        td = friend.to_user
        td = friend.establish
        td = friend.apply
        td = link_to 'Show', friend
        td = link_to 'Edit', edit_friend_path(friend)
        td = link_to 'Destroy', friend, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Friend', new_friend_path

app/views/friends/new.html.slim
h1 new
= @user[0].name
= form_for @friend, url: friends_path do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :to_id, value: @user[0].id
  = f.hidden_field :establish, value: false
  = f.hidden_field :apply, value: true
  = f.submit

app/views/friends/serch.html.slim
h2 フレンドを検索
= form_tag({ :controller => 'friends', :action => 'new' },{ :method => :get }) do
  = label_tag :id
  = text_field_tag 'uniq','', placeholder: "フレンドIDを入力"
  = submit_tag "検索"

- if error.present?
  = error[0]

app/views/friends/show.html.slim
.container
  h2 あなたの友達
  - @your_friends.each do |friend|
    p = friend.name

  h2 あなたと友だちになりたい人たち
  - @users_wanting_to_become_friend_with_you.each do |user|
    p = user.name

app/views/messages/_message.html.slim
/ message_broadcast_job で仕様
.message.panel.panel-primary data-send-user=message.user_id
  .send-user
    p = message.user.name
    p = image_tag("/uploads/user/thumb/#{message.user.icon_img.url.match(/([^\/]+?)?$/)[0]}") if message.user.icon_img.present?
  - if message.image.present?
    = image_tag message.image.url
  - else
    .content
      p = message.content

app/views/rooms/show.html.slim
.container.w-75
  h2 Chat room
  #messages.table data-current-user="#{current_user.id}" data-room-id="#{params[:id]}"
    = render @messages
  #form
    form
      input type='text' data-behavior='room_speaker'
      br/

javascript:
  const crnt_user_id = #{current_user.id};
  $(function () {
    $('#messages').children().each(function () {
      const send_user_id = $(this).data('send-user');
      const direction = crnt_user_id == send_user_id ? 'right' : 'left'
      $(this).addClass(`text-${direction}`);
    });
  });
  // メッセージ追加時
  $('#messages').on('DOMSubtreeModified propertychange', function () {
    const send_user_id = $('#messages .message:last-child').data('send-user');
    const direction = crnt_user_id == send_user_id ? 'right' : 'left'
    $('#messages .message:last-child').addClass(`text-${direction}`);
  });

app/views/users/_edit_form.html.slim
= stylesheet_link_tag 'edit'
.form
  = form_for current_user do |f|
    p 名前を変更
    = f.text_field :name, value: f.object.name
    p メールアドレスを変更
    = f.text_field :email, value: f.object.email
    p フレンドIDを変更
    = f.text_field :user_original, value: f.object.user_original
    p アイコン画像を変更
    = f.label "画像をアップロード"
    = f.file_field :icon_img
    br
    = f.submit "更新", class: 'button'

app/views/users/edit.html.slim
= stylesheet_link_tag 'edit'

- current_user.errors.full_messages.each do |message|
  = message

h1 プロフィールを編集
= render "edit_form"
.button = link_to '戻る', profile_path

app/views/users/index.html.slim
.container
  = link_to 'フレンドを検索', friends_serch_path
  table.table
    thead
      tr
        td 名前
        td アドレス
        td
    tbody
      tr
        td = fa_icon 'user-circle', text: '自分'
        - if user_signed_in?
          td = current_user.email
          td = link_to 'ひとりごと', '#', class: 'btn btn-default'
        - else
          td まだログインしていません
          td

      - @your_friends.each do |user|
        - next if user == current_user
        tr
          td = fa_icon 'user-circle', text: user&.name || '名無しさん'
          td = user.email
          td = link_to 'メッセージルームへ'

app/views/users/profile.html.slim
= stylesheet_link_tag 'users'
.profile
  h1　アカウント情報
  .profile_data
    img src = current_user.icon_img.url
    p = "ユーザー名：#{current_user.name}"
    p = "メールアドレス：#{current_user.email}"
    p = current_user.user_original
  ul.row
    li.list-unstyled.col-sm-6
      .button.channel
        = link_to "チャンネル一覧", channels_path
    li.list-unstyled.col-sm-6
      .button.change
        = link_to "登録内容を変更する",edit_user_path(current_user)